const mongoose= require("mongoose")

const will = mongoose.Schema({

    requesterTitle: { type: String },
    requesterFname: {type:String},
    requesterMname: {type:String},
    requesterLname: {type:String},
    requesterAdd: {type:String},
    requesterEmail: {type:String},
    requesterPhNo: {type:String},
    requesterAddLine1: {type:String},
    requesterAddLine2: {type:String},
    requesterTown: {type:String},
    requesterCountry: {type:String},
    requesterPostCode: {type:String},
    promotionCode: {type:String},
    requesterSelfie: {type:String},
    willStatus:{type:String},
    willOwnerTitle: {type:String},
    willOwnerFname: {type:String},
    willOwnerMname: {type:String},
    willOwnerSurname: {type:String},
    willOwnerEmail:{type:String},
    willOwnerDob: {type:String},
    willOwnerGender: {type:String},
    willOwnerAddLine1: {type:String},
    willOwnerAddLine2: {type:String},
    willOwnerCity: {type:String},
    willOwnerCountry: {type:String},
    willOwnerPostcode: {type:String},
    willOwnerPhNo:{type:String},
    executorName: {type:String},
    executorEmailAdd: {type:String},
    executorPhoneNo: {type:String},
    executorAddLine1: {type:String},
    executorAddLine2: {type:String},
    executorCity: {type:String},
    executorCountry: {type:String},
    storedWillAdd: {type:String},
    additionalIns: {type:String, required: true},
    willReminderFr: {type:String},
    lastRemDate: {type:String},
    nextRemDate: {type:String},
    createdWillPDF: {type:String},
    discountCode: {type:String},
    discountAmount: {type:String},
    dateCreated:{type:String},
    willSource:{type:String},
    createdBy:{type:String},
    willRefNo:{type: Number},
    willStorageRefNo:{type:Number},
    willPDF:{type:String},
    userID: {type: String},
  });

  module.exports = mongoose.model("will", will);
